ESEMPIO ANN DA ZERO IN NUMPY (forward pass)

non usiamo libreria già pronte come keras, ma solo numpy per capire i passaggi (inizializzazione, vettorizzazione del calcolo, mini-batch)

In una rete neurale non calcoliamo un neurone alla volta, con il calcolo vettorializzato di numpy (operazioni tra matrici)

In [1]:
import numpy as np

1) INIZIALIZZAZIONE
(si inizializa con valori casuali molto piccoli)

In [2]:
#definiamo la rete
#3 feature in ingresso e 5 neuroni nello strato nascosto.
input_size = 3
hidden_size = 5
#creiamo i pesi per lo strato nascosto (pesi molto piccoli e diversi)
w = np.random.rand(hidden_size,input_size)*0.01
#creiamo i pesi per lo strato di uscita
b = np.zeros((hidden_size,1))
#definiamo una funzione di attivazione (ReLU)
w,b

(array([[0.00843252, 0.00048237, 0.00668762],
        [0.00874622, 0.00923777, 0.00757389],
        [0.0049854 , 0.00189084, 0.00446029],
        [0.00303344, 0.00831833, 0.00109244],
        [0.003647  , 0.00122637, 0.00299226]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]]))

In [ ]:
#eseguiamo il calcolo dello strato nascosto
#input di esempio (dato in ingresso)
x = np.array([[1],[2],[3]])
x=np.random.randn(input_size,1)
#calcolo dello strato nascosto
z = np.dot(w,x) + b #np.dot esegue il prodotto scalare tra matrice e vettore
z

array([[2.71395307e-03],
       [0.00000000e+00],
       [6.57536628e-04],
       [2.55443925e-05],
       [0.00000000e+00]])

In [9]:
batch_size = 4
x_batch = np.random.randn(batch_size,input_size)
#calcolo vettorizzato, attenzione a trasformare l'array per moltiplicarlo con la matrice 
z_batch = np.dot(w,x_batch.T) + b
#applichiamo la funzione di attivazione ReLU
a = np.maximum(0,z_batch)
a  

array([[0.0004819 , 0.        , 0.        , 0.        ],
       [0.00485523, 0.00070526, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00282777],
       [0.00090375, 0.        , 0.        , 0.        ],
       [0.00024467, 0.        , 0.        , 0.00020224]])