Utilizzando la funzione rnn_cell_forward definita nell'esercizio della lezione, calcola l'evoluzone dello stato nascosto per una sequenza di 3 passi temporali
Input x=[1.1,-0.5,2.0]
Stato iniziale: h_0=[0,0]
Matrici: usa le stesse matrici dell'esempio precedente
 
Crea un ciclo for che iteri sulla sequenza e stampi il valore di h_t a ogni passo. Osserva come lo stasto cambia non solo in base all'input corrente, ma anche in base a ciò che è successo prima

In [1]:
import numpy as np
import tensorflow as tf

# =================================================================
# 1. IMPLEMENTAZIONE MANUALE CON NUMPY
# =================================================================

def rnn_cell_forward(xt, h_prev, Wxh, Whh, bh):
    z_t = np.dot(Wxh, xt) + np.dot(Whh, h_prev) + bh
    h_t = np.tanh(z_t)
    return h_t

# Parametri (invariati)
dim_input = 1
dim_hidden = 2

Wxh = np.array([[0.5], [0.8]])
Whh = np.array([[0.1, 0.2], [0.3, 0.4]])
bh = np.zeros((dim_hidden, 1))

# --- MODIFICA QUI: Sequenza di 3 passi ---
x_sequence = [1.0, -0.5, 2.0] 
h_t = np.zeros((dim_hidden, 1)) # h0 iniziale

print("--- Evoluzione dello Stato Nascosto (Loop) ---")
for i, x_val in enumerate(x_sequence):
    # Trasformiamo il valore scalare in un vettore colonna (1, 1)
    xt = np.array([[x_val]])
    
    # Aggiornamento: lo stato attuale diventa il precedente per il prossimo passo
    h_t = rnn_cell_forward(xt, h_t, Wxh, Whh, bh)
    
    print(f"Passo {i+1} (Input x={x_val}):\n{h_t}\n")

# =================================================================
# 2. VERIFICA CON KERAS (Aggiornato alla sequenza)
# =================================================================

# Prepariamo l'input: (batch, timesteps, features) -> (1, 3, 1)
keras_input = np.array(x_sequence).reshape(1, 3, 1)

rnn_layer = tf.keras.layers.SimpleRNN(units=dim_hidden, activation='tanh', return_state=True)
rnn_layer.build((None, 3, 1))
rnn_layer.set_weights([Wxh.T, Whh.T, bh.flatten()])

output, h_final_keras = rnn_layer(keras_input)

print("--- Verifica Finale con Keras ---")
print(f"Stato finale h3 (Keras):\n{h_final_keras.numpy().T}")

--- Evoluzione dello Stato Nascosto (Loop) ---
Passo 1 (Input x=1.0):
[[0.46211716]
 [0.66403677]]

Passo 2 (Input x=-0.5):
[[-0.07086196]
 [ 0.00424983]]

Passo 3 (Input x=2.0):
[[0.75896264]
 [0.91867079]]

--- Verifica Finale con Keras ---
Stato finale h3 (Keras):
[[0.7589626 ]
 [0.91867083]]
