Crea un Tesore 3D di forma (3,4,5) contenente numeri casuali. Estrai la sesta riga della seconda matrice. Successivamente, trasforma il tensore originale in una forma (5,12) e infine inverti l'ordine delle prime due dimensioni del tensore 3D iniziale. Suggerimento: ricorda che gli indici partono da zero e usa il metodo permute per lo scambio dimensionale multiplo.

In [4]:
import torch
import numpy as np

In [5]:
#1. IL PONTE TRA NUMPY E PYTORCH
#Crea un Tesore 3D di forma (3,4,5) contenente numeri casuali
tensor=torch.randn(3,4,5)
print(f"Tensore \n{tensor}")

Tensore 
tensor([[[-0.3388,  0.2104,  0.8362,  0.2034, -0.4930],
         [-0.4812, -0.2946, -0.2634,  0.3664,  1.4638],
         [-0.4392, -0.0897,  0.0611,  0.4525, -0.1067],
         [-1.2254,  0.0257, -0.2082, -0.2190,  0.6271]],

        [[-2.3061, -0.1128,  0.7080,  0.3396,  1.6216],
         [ 0.5571,  0.2792, -1.6366,  0.7583,  0.4849],
         [ 0.0965,  1.1162, -1.0802, -1.0426, -0.3328],
         [-0.2395,  0.1525,  0.7893, -0.8086,  0.2973]],

        [[ 0.6465, -0.5828,  0.4976, -0.6797, -0.0669],
         [-0.4808,  1.3629, -2.1483, -0.1095, -0.0420],
         [ 0.6273, -1.1473, -1.2543, -0.4417, -0.4631],
         [ 0.0262,  0.6512, -1.9596, -0.8490, -1.9021]]])


In [ ]:
#Estrai la sesta riga della seconda matrice
slice_1=tensor[:,3,:] #non ho la sesta riga, estraggo la 4
print(slice_1)

In [9]:
#trasforma il tensore originale in una forma (5,12) 
tensor_1=tensor.reshape(5,12)
print(tensor_1)

tensor([[-0.3388,  0.2104,  0.8362,  0.2034, -0.4930, -0.4812, -0.2946, -0.2634,
          0.3664,  1.4638, -0.4392, -0.0897],
        [ 0.0611,  0.4525, -0.1067, -1.2254,  0.0257, -0.2082, -0.2190,  0.6271,
         -2.3061, -0.1128,  0.7080,  0.3396],
        [ 1.6216,  0.5571,  0.2792, -1.6366,  0.7583,  0.4849,  0.0965,  1.1162,
         -1.0802, -1.0426, -0.3328, -0.2395],
        [ 0.1525,  0.7893, -0.8086,  0.2973,  0.6465, -0.5828,  0.4976, -0.6797,
         -0.0669, -0.4808,  1.3629, -2.1483],
        [-0.1095, -0.0420,  0.6273, -1.1473, -1.2543, -0.4417, -0.4631,  0.0262,
          0.6512, -1.9596, -0.8490, -1.9021]])


In [10]:
#inverti l'ordine delle prime due dimensioni del tensore 3D iniziale
t_invertito=tensor.transpose(1,0)
print(tensor)
print(t_invertito)

tensor([[[-0.3388,  0.2104,  0.8362,  0.2034, -0.4930],
         [-0.4812, -0.2946, -0.2634,  0.3664,  1.4638],
         [-0.4392, -0.0897,  0.0611,  0.4525, -0.1067],
         [-1.2254,  0.0257, -0.2082, -0.2190,  0.6271]],

        [[-2.3061, -0.1128,  0.7080,  0.3396,  1.6216],
         [ 0.5571,  0.2792, -1.6366,  0.7583,  0.4849],
         [ 0.0965,  1.1162, -1.0802, -1.0426, -0.3328],
         [-0.2395,  0.1525,  0.7893, -0.8086,  0.2973]],

        [[ 0.6465, -0.5828,  0.4976, -0.6797, -0.0669],
         [-0.4808,  1.3629, -2.1483, -0.1095, -0.0420],
         [ 0.6273, -1.1473, -1.2543, -0.4417, -0.4631],
         [ 0.0262,  0.6512, -1.9596, -0.8490, -1.9021]]])
tensor([[[-0.3388,  0.2104,  0.8362,  0.2034, -0.4930],
         [-2.3061, -0.1128,  0.7080,  0.3396,  1.6216],
         [ 0.6465, -0.5828,  0.4976, -0.6797, -0.0669]],

        [[-0.4812, -0.2946, -0.2634,  0.3664,  1.4638],
         [ 0.5571,  0.2792, -1.6366,  0.7583,  0.4849],
         [-0.4808,  1.3629, -2.1483, -0.