Crea due matrici casuali A e B con TensorFlow. La matrice A deve avere forma (3,4), la matrice B (4,2). Esegui la moltiplicazione matriciale e verifica che la forma del risultato sia (3,2). Successivamente, prova a sommare un vettore costante di bias di dimensione 2 sfruttando il broadcasting.
Suggerimento: usa tf.random.normal per generare i dati e l'operatore @ per la moltiplicazione

In [1]:
import tensorflow as tf
import numpy as np

In [14]:
#Crea due matrici casuali A (3,4) e B (4,2)
a=tf.Variable(tf.random.normal([3,4]),name="a")
b=tf.Variable(tf.random.normal([4,2]),name="b")
prodotto=a@b
print(f"a={a}\nb={b}\n\ta*b={prodotto}")

a=<tf.Variable 'a:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.14640689, -0.39713365, -0.5129448 ,  0.67113537],
       [ 0.01731889, -0.7555919 , -0.6739476 , -1.5691001 ],
       [ 0.45420012, -1.2039714 ,  0.46193838, -0.89044   ]],
      dtype=float32)>
b=<tf.Variable 'b:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.2287102 ,  1.2660747 ],
       [ 0.05626807, -0.06400709],
       [-1.3721658 , -0.83104277],
       [-0.64159876, -0.50476444]], dtype=float32)>
	a*b=[[ 0.28438452  0.2982952 ]
 [ 1.8929458   1.4223955 ]
 [-0.02641577  0.7176858 ]]


somma un vettore costante di bias di dimensione (2) sfruttando il broadcastring

In [17]:
a=tf.constant([[1.0,2.0]])
somma=tf.add(prodotto,a)
print(somma)

tf.Tensor(
[[1.2843845  2.2982953 ]
 [2.8929458  3.4223955 ]
 [0.97358423 2.7176857 ]], shape=(3, 2), dtype=float32)
