ESERCIZIO

Dato un piccolo set di stati dell'encoder (vettori casuali) e uno stato del decoder, implementa manualmente una fuzione di calcolo dei punteggi di attenzione tramite prodotto scalare.
Applica la softmax per ottenere i pesi e calcola il vettore di contesto finale
Suggermiento: usa 'numpy' per gestire le operazioni tra vettori e verifica che la somma dei pesi ottenuti sia pari a 1

In [1]:
import numpy as np

def softmax(x):
    """Calcola la funzione softmax per ogni punteggio in x."""
    e_x = np.exp(x - np.max(x)) # Sottraiamo il max per stabilità numerica
    return e_x / e_x.sum()

def manual_dot_product_attention(encoder_states, decoder_state):
    """
    Implementazione manuale del meccanismo di Attention tramite prodotto scalare.
    
    Argomenti:
    encoder_states: Array numpy di forma (n_stati, dim_vettore)
    decoder_state: Array numpy di forma (dim_vettore,)
    
    Ritorna:
    context_vector: Il vettore di contesto finale
    weights: I pesi dell'attenzione (somma = 1)
    """
    
    print("--- 1. Calcolo dei Punteggi (Scores) ---")
    # Calcoliamo il prodotto scalare tra lo stato del decoder e ogni stato dell'encoder
    # dot_product(decoder, encoder_i)
    scores = np.dot(encoder_states, decoder_state)
    print(f"Punteggi grezzi (Dot Product): {scores}")
    
    print("\n--- 2. Calcolo dei Pesi (Softmax) ---")
    # Applichiamo Softmax per trasformare i punteggi in probabilità (pesi)
    weights = softmax(scores)
    print(f"Pesi di attenzione (Alpha): {weights}")
    print(f"Verifica somma pesi: {np.sum(weights):.2f}")
    
    print("\n--- 3. Calcolo del Vettore di Contesto ---")
    # Il vettore di contesto è la somma pesata degli stati dell'encoder
    # context = sum(weight_i * encoder_state_i)
    context_vector = np.dot(weights, encoder_states)
    print(f"Vettore di contesto finale: {context_vector}")
    
    return context_vector, weights

# --- ESECUZIONE ---

# 1. Definiamo i parametri
dim_vettore = 4
n_stati_encoder = 3

# 2. Generiamo vettori casuali per simulare gli stati
np.random.seed(42) # Per riproducibilità
encoder_states = np.random.rand(n_stati_encoder, dim_vettore)
decoder_state = np.random.rand(dim_vettore)

print("Stati dell'Encoder (Memoria):")
print(encoder_states)
print("\nStato del Decoder (Query attuale):")
print(decoder_state)
print("-" * 30)

# 3. Applichiamo la funzione
context, weights = manual_dot_product_attention(encoder_states, decoder_state)

# 4. Verifica finale richiesta
assert np.isclose(np.sum(weights), 1.0), "ERRORE: La somma dei pesi non è pari a 1!"
print("\n[OK] Test superato: La somma dei pesi è esattamente 1.0")

Stati dell'Encoder (Memoria):
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Stato del Decoder (Query attuale):
[0.83244264 0.21233911 0.18182497 0.18340451]
------------------------------
--- 1. Calcolo dei Punteggi (Scores) ---
Punteggi grezzi (Dot Product): [0.75654844 0.33242197 0.83237389]

--- 2. Calcolo dei Pesi (Softmax) ---
Pesi di attenzione (Alpha): [0.36588283 0.23941218 0.39470498]
Verifica somma pesi: 1.00

--- 3. Calcolo del Vettore di Contesto ---
Vettore di contesto finale: [0.41165365 0.66467681 0.28985474 0.80924024]

[OK] Test superato: La somma dei pesi è esattamente 1.0
