OPERAZIONI DI POOLING (MAX, AVERAGE)

Il pooling prende l'enorme quantità di dati della feature-map e la sintetizza.
La sintetizzazione avviene con il max pooling o average pooling

Prende l'enorme quantità di data della feature-map e li sintetizza nei suoi concetti chiave.

Perchè vogliamo perdere risoluzione volontariamente?
Dopo che layer convoluzionali hanno fatto il loro lavoro, abbiamo delle mappe piene di dettagli (le feature map). Ci serve davvero sapere l'essata cordinata di ogni millimetro di ogni singolo pixel di un bordo?. Questi dati contengono ancora troppe informazioni ridondanti. Il downsampling ha lo scopo di ridurre le dimensioni spaziali della rappresentazione. 
Questa operazione non serve solo a risparmiare memoria, ma aiuta la rete a diventare invariante rispetto a piccole traslazioni e distorsioni degli oggetti nell'immagine di input.
Troppa precisione può essere un danno, non vogliamo che se un gatto si sposta di un millimetro la rete pensi che sia un oggetto completamente nuovo. Il downsamplig serve a questo, riduciamo la risoluzione spaziale per estrarre l'essenza dell'informazione, rendendo la rete più flessibile e robusta alle piccole variazioni del mondo reale.

Perchè eseguire il Pooling?
Efficienza e astrazione gerarchica
Il pooling è la nostra arma contro 3 nemici:
1) Costo computazionale: diminuendo la larghezza e l'altezza della mappe, i layer successivi dovranno elaborare un numero inferiore di parametri
2) Overfitting: una rappresentazione meno densa di dettagli superflui costringe la rete a concentrarsi su pattern più robusti e globali invece di memorizzare rumore.
3) Invarianza spaziale: il pooling permette di riconoscere una feature anche se la sua posizione esatta cambia leggermente all'interno della finestra di scansione.
L'operazione trasforma una regione di input in un singolo valore sintetico preservando la profondità dei canali

Meccanismi del Downsampling
- Indipendenza dai canali
A differenza della convoluzione, il pooling agisce su ogni canale di input in modo indipentente. Se la rete ha 64 filtri (feature map), il polling produrrà 64 versioni ridotte.
- Assenza di pesi: il pooling è un'operazione pigra, non ha pesi, non ha bias, non deve imparare nulla, deve solo sintetizzare. Il pooling è un'operazione matematica fissa, che non appesantisce l'apprendimento, ma lo accellera semplificando i dati. Inoltre è un'operazione computazionalmente molto leggera.
- Sommario dell'informazione
Il layer agisce come un filtro che riassume la presenza di una caratteristica specifica in una determinata area, ignorando i dettagli esatti della sua posizione

La piramide dell'astrazione
Nelle architetture moderne (come ResNet VGG assistiamo alla piramide dell'astrazione cioè all'alternanza tra convoluzione e pooling crea una struttura a piramide inverita: la risoluzione spaziale scende mentre il numero di canali (la prodondità semantica) sale.
Sacrifichiamo il dove (la posizione esatta), per guadagnare il cosa, la prodondità semantica.
Questo permette ai layer finali della rete di avere un campo ricettivo globale, vedendo l'immagine nel suo insieme invece di concentrarsi sui singoli pixel.
I layer finali non vedono più pixel, vedono concetti universali come faccia, automobile o fiori, pronti per essere classificati.
Ma come decidiamo quale valore scegliere per il pooling?

Strategia di Pooling
Max Pooling vs Average Pooling
Esistono diversi modi per sintetizzare i valori di una finestra. Le due tecniche dominanti nel Deep Learning moderno sono il Max Pooling e l'Average Pooling.
Scegliere tra queste due opzioni significa decidere se vogliamo premiare il segnale più forte (la feature più evidente) o avere una visione mediata e fluida del contesto. Questa è la differenza tra max pooling e average pooling.
Ognuna delle due tecniche ha un'importante influenza su ciò che la rete vedrà alla fine del processo.

Le Due Facce del Pooling
Massimo impatto contro media contestuale.
- Il Max Pooling seleziona il valore massimo all'interno della finestra, prende il pixel che urla più forte in un'area definita. E' estremamente efficace per catturare bordi, angoli e caratteristiche salienti. Prendendo il massimo preserviamo il segnale più importante.
- L'Average Pooling è uno sfumatore, calcola la media aritmetica di tutto. Tende a conservare più informazioni sullo sfondo e a produrre transizioni più morbide. Rischia di diluire troppo i segnali forti. Utile quando vogliamo una visione d'insieme fluida ma rischia di diluire troppo i segnali forti

Nella pratica, il Max Pooling è lo standard per la classificazione di immagini perchè agisce come un rilevatore di presenza estremamente efficiente.

Parametri d configurazione del layer
1) Dimensione delle finestr (pool size): solitamente si utilizza una finestra 2x2. Finestre più grandi rischierebbero di perdere troppa informazione spaziale fondamentale.
E' il nostro occhiello di osservazione
2) Stride del Pooling (passo): Lo stride è quasi sempre impostato uguale alla dimensione della finestra (es. stride 2 per pool 2x2) per evitare sovrapposizioni e dimezzare esattamente le dimensioni
- Padding nel Pooling: sebbene meno comune che nelle convoluzioni, è possibile usare il padding per gestire input le cui dimensioni non sono mupltipli dello stride.

Confronto Visivo tra Max e Average Pooling
Cosa vede davvero la rete
Immagina un immagine di un cielo stellato, il max pooling manterrebbe la luminosità delle stelle, perchè sono i punti di valore massimo.
Il Max Pooling funge da 'rilevatore di presenza': se una feature è presente anche solo in un pixel della finestra, il valore viene propagato. 
L'average pooling invece farebbe una media tra il nero del cielo ed il bianco delle stelle, rendendo un grigio spento. 
L'average pooling diliusce il segnale.
Per questo motivo, l'Average Poolin viene spesso relegato ai leyer finali (Global Average Pooling) per condensare l'intera immagine prima della classificazione densa. Utiliziamo l'average pooling quando non ci interessano più i contrasti locali, ma vogliamo un voto democratico di tutta l'immagine prima del verdetto finale.

Esempio Analisi della Matrice 4X4
Partiamo da un'immagine 4X4, stride 2, Max Pooling 2x2
Scansione del Quadrante
Il kernel parte dall'angolo in alto a sinistra (pixel 0,0 e 0,1; 1,0 e 1,1). Identifica il massimo e lo scrive nella prima cella dell'output.
Spostamento dello Stride
Con stride 2, il kernel scorre di due colonne a destra (colonna 3, saltando la 2), posizionandosi sull'area 0,2 e 0,1 e 1,2 e 1,3 per calcolare il secondo valore.
Completamento della Riga
Il processo prosegue scendendo di due righe finchè l'intera matrice originale non è stata sintetizzata nella nuova forma compressa.
Tutto questo si traduce in una singola riga di codice in Keras

Dall'esercizio al Codice
Sintesi Keras per il Pooling
In Keras, l'operazoine si implementa con: 
layers.MaxPooling2D(pool_size=(2,2),stirde=(2,2)) 
Per default lo stride segue la pool_size, pertanto non servirebbe specificare lo stride se uguale al pool_size perchè il framework di Keras lo capisce da solo.

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

# --- 1. PREPARAZIONE DATI (Punto chiave 3) ---
# Creiamo una matrice 4x4 di prova per simulare una Feature Map
# Aggiungiamo le dimensioni per Batch e Canali: (1, 4, 4, 1)
data = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [50, 60, 70, 80],
    [55, 65, 75, 95]
], dtype=np.float32).reshape(1, 4, 4, 1)

# --- 2. MAX POOLING (Punto chiave 2) ---
# Estrae il valore massimo in ogni finestra 2x2
max_pool_layer = layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2))
max_output = max_pool_layer(data)

# --- 3. AVERAGE POOLING (Punto chiave 2) ---
# Calcola la media in ogni finestra 2x2
avg_pool_layer = layers.AveragePooling2D(pool_size=(2, 2), strides=(2, 2))
avg_output = avg_pool_layer(data)

print("Matrice Originale 4x4:\n", data.reshape(4, 4))
print("\nRisultato Max Pooling 2x2 (Sintesi dei picchi):\n", max_output.numpy().reshape(2, 2))
print("\nRisultato Average Pooling 2x2 (Sintesi media):\n", avg_output.numpy().reshape(2, 2))

Matrice Originale 4x4:
 [[10. 20. 30. 40.]
 [15. 25. 35. 45.]
 [50. 60. 70. 80.]
 [55. 65. 75. 95.]]

Risultato Max Pooling 2x2 (Sintesi dei picchi):
 [[25. 45.]
 [65. 95.]]

Risultato Average Pooling 2x2 (Sintesi media):
 [[17.5 37.5]
 [57.5 80. ]]


Rimpicciolire i dati con downsampling è il segreto per l'efficienza e la robustezza.
Il max pooling è il nostro evidenziato per i dettagli salienti
L'average pooling offre una sintesi più sfumata e globale
L'uso di pool 2x2 e stride 2 dimezza le dimensioni spaziali, dimezzando la risoluzione e permettendo alla rete di astrarre pattern gerarchici.
Pronti per progettare reti che sanno distinguere l'essenziale dal superfluo.

Le operazioni di pooling riducono la dimensione spaziale delle feature map mantenendo le informazioni più rilevanti.

I principali tipi sono:

Max Pooling → mantiene il valore massimo
Average Pooling → mantiene la media
Global Average Pooling → riduce ogni feature map a un singolo valore

I vantaggi sono:

meno memoria
meno calcoli
meno overfitting
maggiore robustezza a piccoli spostamenti degli oggetti nell'immagine