IL MODELLO BAG OF WORDS (BoW)

Il modello Bag of Words (BoW) è uno dei modelli piu' semplici e importanti per trasformare del testo in numeri.

Prendo un testo e rappresento quante volte compaiono certe parole, ignoradno quasi completamente l'ordine e la struttura grammaticale.

Il nome 'sacchetto di parole' rende bene l'idea: immagina di mettere tutte le parole in un sacchetto e contare quante volte compare ciascuna parola

Il punto di partenza per trasformare il linguaggio naturale in un formato comprensibile dalle rete neurali è la creazione di un vocabolario. Questo rappresenta l'insieme di tutti i termini unici estratti dal corpus dopo le fasi di preprocessing (lemmatizzazione e rimosso le stop words).
Non ci interessa la frase nella sua interezza, ma i singoli elementi.
Costruire un vocabolario significa assegnare a ogni termine un identificativo numerico univoco. In questo modo, ogni parola diventa un indice in un array, permettendo la successiva conversione in vettori matematici pronti per l'elaborazione.
Ma come gestiamo questo passaggio dallle stringhe agli indici numerici?
Il segreto è la mappatura

Meccanismi di Indicizzazione
Come gestire la variabilità del linguaggio
Ogni parola unica viene associata ad un intero (Word-to-ID), ogni intero è associato as una sola parola (associazione biunivoca)
Dobbiamo però fare un scelta di campo: la dimensione del vocabolario. Scelta del numero di parole da mantenere per bilanciare precisione semantica e complessità computazionale.
Se dovessimo mettere tutte le parole il vocabolario sarebbe enorme ed il modello ingestibile. Vogliamo quelle essenziali per capire il senso lasciando fuori le rarità che creerebbero solo confuzione. 
L'insieme dei termini unici definisce lo spazio delle caratteristiche di input per il modello.

Ma cosa succede se il modello incontra una parola che non ha mai visto prima?

Gestione del Lessico
Quando il modello incontra parole non presenti nel vocabolario originale durante la fase di test, queste vengono solitamente mappate verso un token speciale chiamato 'UNK' (termini Out-of-Vocabulary OOV)
Per evitare vocabolari troppo vasti, si escludono le parole con frequenza troppo bassa (esempio parole che compaiono una sola volta in milioni di pagine, spesso sono errori di battitura o nomi propri), che non portano valore statistico.
Inoltre, rimuovere le parole comuni (vedi esempio piu' sotto con la parola ordine) permette di concentrare il vocabolario su termini che descrivono realmente il contenuto informativo del documento (filtro stopwords)
Eliminare queste parole non è solo pulizia, ma evita di confondere il modello.

C'è un ordine logico in questo elenco di parole?

Approfondimento: Ordinamento e Ranking
Selezione delle Feature
L'ordinamento dei termini nel vocabolario non è casuale ed è fondamentale per il ranking. Spesso i termini vengono ordinati per frequenza decrescente, permettendo al modello di selezionare le 'top-k' parole piu' rilevanti. E' possibile tenere le prime 5/10.000 parole e scartiamo tutto il resto.
Definiamo la cardinalità del vocabolario come il numero totale di elementi unici estratti dal testo.
La cardinalità determina quanto sarà grande la nostra matrice finale. Piu' la carinalità è grande, piu' il modello sarà preciso, ma allo stesso tempo, affamato di risorse computazionali (classico problema del Deeop Learning).

Ora possiamo costruire la nostra matrice

La Matrice Documento-Term (DTM)
Il cuore del modello BAg of Words.
Una volta definito il vocabolario, possiamo rappresentare ogni documento come un vettore. La matrice Document-Term è una struttura dove ogni riga corrisponde a un documento e ogni colonna a un termine del vocabolario.
Il valore all'interno di ogni cella rappresenta la frequenza di una parola in quel determinato documento. Si chiama 'Bag of Words' perchè l'ordine delle parole viene ignorato, focalizzandosi solo sulla presenza e frequenza.
In questa matrice l'ordine della parolo è sparito, la sintassi anche. L'ordinamento per frequenza ci era servito solo per tenere le n parole con frequenza piu' alta, ma poi le parole vengono mescolate perdendo ogni tipo di ordinamento.

Vediamo come si riempieno queste cella con i numeri.

Vetorizzazione e Conteggio
dal testo alla matrice numerica
Parto da un array di dimensioni pari al vocabolario dove ogni posizione indica quante volte quella parola appare nel testo (vettore documento).
Ogni parola è trattata come una dimensione indipendente, ignorando la semantica della vicinanza.
Tuttavia, questa rappresentazione quantitativa è importantissima per confrontare documenti. Se due vettori hanno numeri alti nelle stesse colonne, significa che piu' o meno parlano degli stessi argomenti.
La matrice cattura la 'densità' dei termini, permettendo operazioni di confronto tra documenti.
Ogni elemento della matrice rappresenta il conteggio del termine j-esimo nel documento i-esimo 

Cosa succede a livello di singola parola?
A livello atomico, ogni parola può essere vista come un vettore con un unico valore '1' in corrispondenza del suo indice nel vocabolario (vettori One-Hot)
Il vettore del documento BoW è la somma algebrica dei vettori one-hot di tutte le parole che lo compongono (aggregazione vettoriale)
Poichè sommiamo i conteggi, le frasi "il cane morde l'uomo" e "l'uomo morde il cane" produrrano vettori identici (perdita di sintassi)

Rappresentare i documenti come vettori ci permette di calcolare la similarità tra testi utilizzando la distanza euclidea o la similarità coseno in uno spazio a n-dimensioni.
LA distanza tra due documenti d1 e d2 può essere misurata tramite la norma vettoriale della loro differenza.
E' quindi possibile definre quanto due recensioni sono simili, aprendo la strada alle recensione ad al clustering.

Prendiamo due frasi:NON CAPISCE il contesto
frase 1: "cliente ordina prodotto"
frase 2: "cliente riceve prodotot"
Costruiamo il vocanolario complessivo:
cliente, ordina, prodotto, riceve
Ora trasformiamo ogni frase in un vettore:
cliente ordina  prodotto    riceve
1       1       1           0           [1,1,1,0]
cliente ordina  prodotto    riceve
1       0       1           1           [1,0,1,1]
A questo punto il testo è diventato numerico e può essere dato al Machine LEarning
Quindi la pipeline e:
testo -> tokenizzazione -> vocabolario -> conteggio parole -> vettore numerico -> modello ML
Per esempio:
mail -> Bag of Words -> logistic regression (ML) -> ordine/reclamo/offerta
Questo è NLP classico
La cosa importante è che il vocabolario viene costruito sul testo, cioè sull'insieme dei documenti

Il primo grande limite di Bag of Words è che non capisce il significato
La frase "cliente ordina prodotto " e la frase "prodotto ordina prodotto" hanno lo stesso vettore, anche se l'ordine delle parole è diverso e diverso il significato

Quindi BoW sa QUALI parole ci sono e sa QUANTE volte compaiono
NON sa bene in che ORDINE compaiono e NON CAPISCE il contesto,
nel sacchetto (bag) perdi l'ordine

Altro esempio:
la frase "merce disponibile" e la frase "merce non disponibile" con BoW diventano due vettori molto simili, se poi fai pre-processing ed elimini "non" con stopword, rischi di rendere le due frasi idnetiche (pur avendo un significato completamente diverso)
Quindi IL PRE-PROCESSING DEVE ESSERE FATTO CON ATTENZIONE

Altro problema
Per frasi lunghe (supponi 50.000 parole) il vettore della frase è molto lungo (fino al massimo a 50.000) se poi ho due frasi i due vettori saranno ancora piu' lunghi e spesso piene di zeri. Ogni documento utilizza solo una minuscola frazione dell'intero vocabolario disponibile.

Questa situazione si chiama SPARSITA'
Hai quindi una matrice sparsa (SPARSE MATRIX) che è appunto uno dei limiti di BoW

Gestire queste matrici come array densi porterebbe a un esaurimento immediato della memoria RAM, specialmente con corpora di grandi dimensioni ovocabolari di migliaia di termini.

Altro probelma: tutte le parole vengono trattate inizialmente allo stesso modo
Le parole il, la, di (ed altre simili) contribuiscono allo stesso modo di altre parole (tipo cliente, ordina, prodotto) alla creazione del vettore
Per questo BoW viene spesso combinato con STOPWORD REMOVAL oppure con TF-IDF

Come possiamo essere piu' intelligenti nel conservare questi dati nel vocabolario?

La soluzione sono le matrici sparse, invece di annotare ogni singola cella, diciamo al computer "segnati solo dove ci sono valori diversi da zer ed ignora tutto il resto" 
Formati come CSR o CSC memorizzano solo i valori diversi da zero e le loro coordinate.
In questo modo l'efficienza Computazionale ne beneficia, le operazioni algebriche sono ottimizzate per saltare i calcoli inutili sugli zeri durante l'addestramento.

Oltre al fomrato di salvataggio (appena visto) quali altre strategia abbiamo?

Strategia di Contenimento
Impostare parametri come 'max_features' permette di limitare le colonne della matrice ai soli termini statisticamente significativi (Trimming del Vocabolario)
Utilizzare interi a 8 o 16 bit per i conteggi invece di float a 64 bit per dimezzare l'ingombro dei dati.

Rappresentazioni CSR
Compressed Sparse Row
Il formato CSR memorizza tra array: i valori non nulli, gli indici di colonna e i puntatori di riga. E' lo standard utilizzato da librerie come Scikit-learn pr la vettorizzazione.
In una matrice sparsa, il risparmio di memoria è proporzionale al numero di zeri presenti.

Ricorda, in NLP la gestine efficiente della memoria è importante quanto l'architettura stessa.

TF-IDF

TF-IDF è sostanzzialmente un miglioramento della rappresentazione Bag of Words: invece di dire solamente : "questa parola compare 10 volte" dice "questa parola compare molto in questo documento, ma quanto è rara o comunque nell'intero corpus?"
per esempio "cliente" potrebbe comparire in quasi tutte le mail e quindi essere poco discriminante, mentre"reclamo" potrebbe comparire solo nelle mail effettive di reclamo e quindi avere un peso maggiore
Quindi:
Bag of Words -> conteggio
TF-IDF -> conteggio pesato per importanza

Un altro miglioramento di BoW sono con gli N-gram
BoW classico con unigrammi:
richiesta
offerta

BoW con bigrammi:
richiesta offerta
Questo recupara un po di contesto locale

In [1]:
import numpy as np

"""
PIPELINE DI ELABORAZIONE: BAG OF WORDS (BoW)
-------------------------------------------
Questo script implementa da zero il modello Bag of Words, una tecnica fondamentale
di elaborazione del linguaggio naturale (NLP) per convertire testo non strutturato
in dati numerici comprensibili dagli algoritmi di Machine Learning.

LOGICA DEL PROCESSO:
1. Tokenizzazione: Scomposizione del testo in singole parole (token).
2. Normalizzazione: Pulizia del testo (minuscolo, rimozione punteggiatura).
3. Vocabolario: Creazione di un elenco unico di parole note.
4. Vettorizzazione: Ogni documento diventa un vettore di frequenze basato sul vocabolario.
"""

# 1. DEFINIZIONE DEL CORPUS DI ESEMPIO
# Il 'corpus' è l'insieme di tutti i documenti (frasi) che vogliamo analizzare.
# Ogni stringa rappresenta un "documento" separato.
corpus = [
    "Il Deep Learning è affascinante.",
    "Le reti neurali leggono i dati.",
    "Il Deep Learning usa le reti neurali."
]

print("--- 1. Costruzione del Vocabolario ---")
# PASSO A: Pulizia e Tokenizzazione aggregata
# .join(corpus): Unisce tutte le frasi in un unico blocco di testo.
# .lower(): Uniforma il testo per evitare che "Il" e "il" siano contati come parole diverse.
# .replace(".", ""): Rimuove la punteggiatura che non porta significato semantico.
# .split(): Divide il testo in una lista di singole parole.
all_tokens = " ".join(corpus).lower().replace(".", "").split()

# PASSO B: Estrazione termini unici (Vocabolario)
# set(all_tokens): Elimina istantaneamente tutti i duplicati.
# sorted(list(...)): Ordina alfabeticamente per avere una mappatura coerente e prevedibile.
vocabulary = sorted(list(set(all_tokens)))

# PASSO C: Mapping Indice-Parola
# creiamo un dizionario dove ogni parola è associata a un ID numerico (la sua posizione nel vettore).
# Questo è fondamentale: la colonna 'n' della matrice corrisponderà sempre alla parola 'word_to_id[n]'.
word_to_id = {word: i for i, word in enumerate(vocabulary)}

print(f"Vocabolario ({len(vocabulary)} termini): {vocabulary}")
print(f"Mappatura: {word_to_id}\n")

# 2. CREAZIONE DELLA MATRICE DOCUMENT-TERM (DTM)
# Una DTM è una rappresentazione tabellare:
# - Righe (i): I singoli documenti del corpus.
# - Colonne (j): I termini presenti nel vocabolario.
# Inizializziamo una matrice di zeri con dimensioni [Num_Documenti x Dim_Vocabolario]
dtm = np.zeros((len(corpus), len(vocabulary)))

# POPOLAMENTO DELLA MATRICE (Vettorizzazione)
# Iteriamo su ogni documento per contare quante volte appare ogni parola del vocabolario.
for i, doc in enumerate(corpus):
    # Ripetiamo la pulizia per il singolo documento
    words = doc.lower().replace(".", "").split()
    for word in words:
        if word in word_to_id:
            # Identifichiamo la colonna corrispondente alla parola corrente
            index = word_to_id[word]
            # Incrementiamo il conteggio nella cella (riga documento, colonna parola)
            dtm[i, index] += 1

print("--- 2. Matrice Document-Term (BoW) ---")
# Ogni riga della matrice è ora la rappresentazione numerica della frase corrispondente.
print(dtm)

# 3. ANALISI DELLA SPARSITÀ
# Concetto Chiave: In NLP, se il vocabolario è di 50.000 parole e una frase ne contiene 10,
# il 99.9% della riga sarà composto da zeri. Questa è la "Sparsità".
# Formula: (Numero di zeri) / (Totale elementi della matrice)
num_nonzero = np.count_nonzero(dtm)
total_elements = dtm.size
sparsity = 1.0 - (num_nonzero / total_elements)

print(f"\n--- 3. Metriche del Dataset ---")
print(f"Elementi totali: {total_elements}")
print(f"Elementi non nulli: {num_nonzero}")
print(f"Sparsità della matrice: {sparsity * 100:.2f}%")
print("Nota: Un'alta sparsità indica che il modello BoW consuma molta memoria per pochi dati utili.")

--- 1. Costruzione del Vocabolario ---
Vocabolario (12 termini): ['affascinante', 'dati', 'deep', 'i', 'il', 'le', 'learning', 'leggono', 'neurali', 'reti', 'usa', 'è']
Mappatura: {'affascinante': 0, 'dati': 1, 'deep': 2, 'i': 3, 'il': 4, 'le': 5, 'learning': 6, 'leggono': 7, 'neurali': 8, 'reti': 9, 'usa': 10, 'è': 11}

--- 2. Matrice Document-Term (BoW) ---
[[1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]]

--- 3. Metriche del Dataset ---
Elementi totali: 36
Elementi non nulli: 18
Sparsità della matrice: 50.00%
Nota: Un'alta sparsità indica che il modello BoW consuma molta memoria per pochi dati utili.
